### ISSUE TITLE
Mod Gameplay Suggestions

### ISSUE THREAD

**Issue by aqueousv2** [Wynd/mineminenomi#169]
- As not all marine much less pirates know how to use the six powers, make it that humans don’t get the six powers automatically when they reach a certain doriki and that they have to do a quest or special training to unlock.

- Make doriki work in conjunction with stats. I Know you want to keep the game balanced, but it would be more interesting if you add individual stats such as strength, speed, swordsmanship, marksmanship, hand to hand combat and intelligence etc.

- With that said doriki can be used as the stat that determine speed and strength be it shouldn’t determine other things such as intelligence and marksmanship, it believe use should have the other stats Because doriki accounts for physical strength only in the one-piece world the amount of doriki shouldn’t determine the skills such as hand to hand combat and swordsmanship.

- Also upgrading these stats can augment the strength of attacks (skills and some devil fruits) e.g. the higher level of swordsmanship stats you have Stronger or stronger variation of sword skill you will be able to use if you cannot obtain a sword skill with that require 50 in stat when you only have 15. So, upgrading certain stats can be one of the criteria to unlock certain skills. The amount of points you have in each stat when you start is dependent on your race and the limit to which you can have is also dependent on race as well.

Hand to hand – Kempos( if you add them), Sabo’s dragon claw, Black leg, the Mink’s Electro(again if you add it)
Swordsmanship-Sword skills
Marksmanship- usopp abilities, kuga bow???

- You can also have devil fruit points that allows you to unlock df abilities because when you eat df the more you use it or kill with it the more points you get and the higher amount of intelligence stat you have the faster you get points because you must understand your powers to make effective use of them and df points allows you to upgrade the strength of df abilites. Upon maxing out the df you can awaken your df.

Just to clarify:
Df points- unlock df abilities as well as upgrade thei abilities
Skill points – unlock and upgade skills

- Also I would like to note the intelligence stat can be used to learn skills like read poneglyphs and read blueprints to make devices for eg raid suits ( if you add them). Thanks for allowing to give a few suggesting and really great mod.

**Comment by FGpisces** [comment]
Hi, to answer your suggestions:

- giving all Humans rokushiki through doriki as the concept for race techniques is the best alternative to cyborgs having all their abilities and fishmen having karate, so as of now, we don't plan to change that, as it would make the humans harder to play as compared to others. We decided that right now, only fighting classes will have quests for their abilities (to be implemented soon)
- we decided against having stats, because we think it's just a redundant rpg aspect that other mods add anyway. As for the devil fruits, we also won't do an upgrade system for them, since it's also just another rpg aspect we think isn't necessary, the way to get better would just be learning how to properly use all abilities instead of grinding to make them stronger
- swordsman and sniper abilities are already in the game, so I don't really know what you mean by that, and other races and classes are planned, along with new fighting styles
